import React, { useState, useRef } from 'react'
import "@/public/styles/ChatBot.css"
import { ArrowUp, Loader2 } from 'lucide-react'
import ChatBody from './ChatBody'
import ChatMessages from './ChatMessages'

type ChatMessage = {
    role: 'user' | 'assistant'
    content: string
}

const ChatBot: React.FC = () => {
    const textareaRef = useRef<HTMLTextAreaElement | null>(null)

    const [message, setMessage] = useState('')
    const [loading, setLoading] = useState(false)
    const [messages, setMessages] = useState<ChatMessage[]>([])
    const [hasStarted, setHasStarted] = useState(false)

    /* Auto-grow textarea */
    const handleInput = (e: React.FormEvent<HTMLTextAreaElement>) => {
        const textarea = textareaRef.current
        if (!textarea) return

        textarea.style.height = 'auto'
        textarea.style.height = `${textarea.scrollHeight}px`
        setMessage(e.currentTarget.value)
    }

    /* Send message */
    const sendMessage = async () => {
        if (!message.trim() || loading) return

        setHasStarted(true)

        const userMessage = message.trim()

        setLoading(true)
        setMessage('')
        textareaRef.current && (textareaRef.current.style.height = 'auto')

        setMessages(prev => [...prev, { role: 'user', content: userMessage }])

        try {
            const res = await fetch('/api/chat', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ message: userMessage })
            })

            const data: { reply: string } = await res.json()

            setMessages(prev => [
                ...prev,
                { role: 'assistant', content: data.reply }
            ])
        } catch (err) {
            console.error('Chat error:', err)
        } finally {
            setLoading(false)
        }
    }

    const startNewChat = () => {
        setMessage('')
        setHasStarted(false)

        if (textareaRef.current) {
            textareaRef.current.style.height = 'auto'
        }
    }

    const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            setHasStarted(true)
            e.preventDefault()
            sendMessage()
        }
    }

    return (
        <main className="relative">
            {/* Header */}
            <div className="flex justify-between items-center">
                <button className="newChatBtn px-4 py-2" onClick={startNewChat}>New Chat</button>

                <div className="chatTitle">Hii, Siddhesh</div>

                <button className="expBtn px-4 py-2 hidden md:flex">
                    Contact Expert
                </button>
            </div>

            {/* Body */}
            <div className="h-[76vh] center flex-col chatBody">
                {!hasStarted ?
                    (<ChatBody
                        onQuickMessage={setMessage}
                    />)
                    : (<ChatMessages messages={messages} loading={loading} />)}
            </div>

            {/* Input */}
            <div className="searchSection flex flex-col pt-4 gap-4">
                <div className="searchBar flex p-4 relative w-[90%] lg:w-[60%]">
                    <textarea
                        ref={textareaRef}
                        value={message}
                        placeholder="Let’s shape your career path together…"
                        onInput={handleInput}
                        onKeyDown={handleKeyDown}
                        rows={1}
                        className="chat-input"
                        disabled={loading}
                    />

                    <button
                        className="p-2"
                        onClick={sendMessage}
                        disabled={loading}
                        aria-label="Send message"
                    >
                        {loading ? (
                            <Loader2 className="animate-spin" size={18} />
                        ) : (
                            <ArrowUp />
                        )}
                    </button>
                </div>

                <p className="text-xs md:text-[14px] text-center text-gray-500 px-4">
                    Responses are generated by AI. They are for learning and exploration purposes only.
                </p>
            </div>
        </main>
    )
}

export default ChatBot
